language: python
sudo: false
python:
- 3.6
install:
- python setup.py install
- pip install coverage
- pip install coveralls
script:
- nosetests -v --with-coverage --cover-tests --cover-package=vanilla_option_pricing
- coveralls